package com.steve.authority.admin.dao;

import com.steve.authority.admin.model.SysMenu;
import com.steve.authority.admin.model.SysMenuKey;

public interface SysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sun Jul 05 10:44:23 CST 2020
     */
    int deleteByPrimaryKey(SysMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sun Jul 05 10:44:23 CST 2020
     */
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sun Jul 05 10:44:23 CST 2020
     */
    int insertSelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sun Jul 05 10:44:23 CST 2020
     */
    SysMenu selectByPrimaryKey(SysMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sun Jul 05 10:44:23 CST 2020
     */
    int updateByPrimaryKeySelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sun Jul 05 10:44:23 CST 2020
     */
    int updateByPrimaryKey(SysMenu record);
}