package com.steve.authority.admin.model;

public class SysConfigKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.variable
     *
     * @mbg.generated Sun Jul 05 10:44:23 CST 2020
     */
    private String variable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.variable
     *
     * @return the value of sys_config.variable
     *
     * @mbg.generated Sun Jul 05 10:44:23 CST 2020
     */
    public String getVariable() {
        return variable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.variable
     *
     * @param variable the value for sys_config.variable
     *
     * @mbg.generated Sun Jul 05 10:44:23 CST 2020
     */
    public void setVariable(String variable) {
        this.variable = variable == null ? null : variable.trim();
    }
}